[package]
name = "custom-dns-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
cookie-factory = "0.3.2"
nom = "7.1.3"
rand = "0.8.5"
thiserror = "1.0.43"
ux = "0.1.5"
